name = "inkspot"
compatibility_date = "2024-08-11"

# [vars]
# MY_VAR = "my-variable"
[vars]
#accelerate_url
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZGIxMTVmZDAtNGE0My00YWM3LTk2MTAtZGU3NTViM2U0M2FlIiwidGVuYW50X2lkIjoiYWU4ZjI3YjZjMDRmZjRlYjkyNjZhZmY3MGIwNWI5NTBhNDhmMDQ2NjM2YzFiYTNhMTY2NTdiMmUxNDg3MGI2NSIsImludGVybmFsX3NlY3JldCI6IjkwNDQ1NjA3LTFkYWMtNDlmNy04NjI2LTA3MjAzODdkMDBiNyJ9.Q5kRnnYQhZmhWcQJ6hT5Jk1nP0BnDuCsliElEU5kawI"
JWT_SECRET = "secret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"